apiVersion: v1
kind: Pod
metadata:
  name: printenv-01
  namespace: istio-test
  labels:
    app: printenv
spec:
  containers:
  - name: workloadentry-test
    image: louhwz/http_server_print_env:0.1
    imagePullPolicy: IfNotPresent
    env:
    - name: printwhat
      value: "影魔"
    ports:
    - containerPort: 80
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: printenv-02
  namespace: istio-test
  labels:
    app: printenv
spec:
  containers:
  - name: workloadentry-test
    image: louhwz/http_server_print_env:0.1
    imagePullPolicy: IfNotPresent
    env:
    - name: printwhat
      value: "剑圣"
    ports:
    - containerPort: 80
  restartPolicy: Always