apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
    - nodePort: 8081
      targetPort: 80
      protocol: TCP
      name: http
      port: 80
    - nodePort: 443
      protocol: TCP
      name: https
      port: 80
  selector:
    app: nginx