apiVersion: apps/v1
kind: Deployment
metadata:
  name: four-type-deployment
spec:
  selector:
    matchLabels:
      app: prometheus-go-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: prometheus-go-demo
    spec:
      containers:
        - name: go-demo
          image: louhwz/prometheus-golang:0.1.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 50m