apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
    - nodePort: 31080
      targetPort: 80
      protocol: TCP
      name: http
      port: 80
    - nodePort: 31443
      protocol: TCP
      name: https
      port: 443
  selector:
    app: nginx